version: "3.8"

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: dukaan-server
    ports:
      - "3001:3001"
    environment:
      - DB_NAME=dukaan
      - DB_USER=user
      - DB_PASS=password
      - DB_HOST=dukaan-mysql
      - DB_DIALECT=mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: dukaan-mysql
    environment:
      MYSQL_DATABASE: dukaan
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
